# Pre-commit hooks configuration
# See https://pre-commit.com for more information

repos:
  # General file checks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
        args: ['--maxkb=10000']  # Prevent files > 10MB
      - id: check-merge-conflict
      - id: debug-statements
      - id: mixed-line-ending

  # Python code formatting
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.10
        args: ['--line-length=100']

  # Python linting
  # - repo: https://github.com/pycqa/flake8
  #   rev: 7.0.0
  #   hooks:
  #     - id: flake8
  #       args: ['--max-line-length=100', '--extend-ignore=E203,W503']

  # Type checking (optional - uncomment if you want it)
  # - repo: https://github.com/pre-commit/mirrors-mypy
  #   rev: v1.8.0
  #   hooks:
  #     - id: mypy
  #       args: ['--ignore-missing-imports']
  #       additional_dependencies: [types-PyYAML]

  # Run pytest tests
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: bash -c 'PRECOMMIT=1 pytest tests/ -v -m "not slow"'
        language: system
        pass_filenames: false
        always_run: true
